# Generated by Django 4.2.7 on 2023-12-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_avto_price_alter_avto_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avto',
            name='price',
            field=models.IntegerField(default=15000, max_length=1000),
        ),
        migrations.AlterField(
            model_name='avto',
            name='year',
            field=models.IntegerField(),
        ),
    ]
