# Generated by Django 4.2.7 on 2023-12-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_avto_price_alter_avto_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='avto',
            name='model',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='avto',
            name='price',
            field=models.IntegerField(default=15000, max_length=30),
        ),
    ]
